server.port=${SERVER_PORT:8080}
spring.application.name=laptop-ordering-backend

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
app.jwt.secret-key=${JWT_SECRET_KEY}
app.jwt.access-token-ttl=${JWT_ACCESS_TOKEN_TTL:15m}
app.jwt.refresh-token-ttl=${JWT_REFRESH_TOKEN_TTL:7d}

# Stripe
stripe.secret.key=${STRIPE_SECRET_KEY}

# VNPay
vnpay.tmn-code=${VNPAY_TMN_CODE}
vnpay.secret-key=${VNPAY_SECRET_KEY}
vnpay.pay-url=${VNPAY_PAY_URL}
vnpay.api-url=${VNPAY_API_URL}
vnpay.return-url=${VNPAY_RETURN_URL}

aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=us-east-1
aws.bucketName=lms-upload-ducvan

# Upload
app.upload.dir=${UPLOAD_DIR:uploads/avatars}

logging.level.org.springframework.security=DEBUG
server.error.include-message=always
